// This file is generated by scripts/generate-tauri-events.mjs
//
// Source of truth: src-tauri/src/events.rs
//
// Do not edit by hand.

export const BACKEND_EVENT_NAMES = [
	"pipeline-state-changed",
	"pipeline-error",
	"pipeline-recording-started",
	"pipeline-transcription-started",
	"pipeline-routing-started",
	"pipeline-rewriting-started",
	"pipeline-transcript-ready",
	"pipeline-reset",
	"pipeline-cancelled",
	"recording-start",
	"recording-stop",
	"overlay-audio-level",
	"overlay-hide-requested",
	"overlay-ocr-context-unavailable",
	"mic-test-audio-level",
	"history-changed",
	"stats-changed",
	"settings-changed",
	"transcript-copied-to-clipboard",
	"single-instance-activated",
	"system-event",
	"connection-state-changed",
	"request-disconnect",
	"quick-ask-started",
	"quick-ask-answer",
	"quick-ask-dismiss-requested",
	"local-whisper-model-load",
	"whisper-model-download-progress",
] as const;

export type BackendEventName = (typeof BACKEND_EVENT_NAMES)[number];

