import { DEFAULT_ACCENT_HEX } from "../accentColor";
import { DEFAULT_STT_LANGUAGE } from "../sttLanguages";
import type {
	AppSettings,
	ProxySettings,
	RewriteProgramPromptProfile,
} from "./types";

export const DEFAULT_SETTINGS_VERSION = 8;
export const DEFAULT_STT_PROVIDER = "groq";
export const DEFAULT_OCR_MODEL = "lightonai/LightOnOCR-1B-1025";

export const DEFAULT_PROXY_SETTINGS: ProxySettings = {
	mode: "system",
	manual: {
		proxy_url: "",
		no_proxy: "localhost,127.0.0.1",
		username: "",
		password: "",
	},
	trusted_ca_certificates: [],
	danger_accept_invalid_certs: false,
};

export const DEFAULT_REWRITE_PROFILE: RewriteProgramPromptProfile = {
	id: "default",
	name: "Default",
	program_paths: [],
	disabled: false,
	cleanup_prompt_sections: null,
	presets: [],
	default_preset_id: null,
	default_preset_description: null,
	default_target_rewrite_llm_enabled: true,
	router: null,
	active_preset_id: null,
	rewrite_llm_enabled: null,
};

export const DEFAULT_SETTINGS_VALUES = {
	settings_version: DEFAULT_SETTINGS_VERSION,
	hotkey_debug_enabled: false,
	selected_mic_id: null,
	sound_enabled: true,
	audio_cue: "kolboo",
	accent_color: DEFAULT_ACCENT_HEX,
	rewrite_llm_enabled: false,
	quick_replace_enabled: false,
	cleanup_prompt_sections: null,
	rewrite_program_prompt_profiles: [DEFAULT_REWRITE_PROFILE],
	// Keep runtime-overlapping defaults aligned with Rust defaults. If a caller
	// needs to represent “unset in the store”, use the raw store value instead of
	// this canonical effective Settings View default.
	stt_provider: DEFAULT_STT_PROVIDER,
	stt_model: null,
	stt_language: DEFAULT_STT_LANGUAGE,
	stt_transcription_prompt: null,
	stt_use_managed_inference: true,
	stt_live_output: false,
	stt_simulated_streaming: false,
	aquavoice_base_url: null,
	whisper_server_base_url: null,
	ollama_url: null,
	local_whisper_model_id: null,
	local_whisper_load_mode: "manual",
	proxy_settings: DEFAULT_PROXY_SETTINGS,
	llm_provider: null,
	llm_model: null,
	quick_ask_provider: null,
	quick_ask_model: null,
	quick_ask_system_prompt: null,
	quick_ask_dismiss_mode: "manual",
	quick_ask_include_selected_text: false,
	windows_clipboard_fallback_for_context_capture: false,
	quick_ask_conversation_history_enabled: true,
	quick_ask_conversation_history_count: 3,
	quick_ask_openai_reasoning_effort: null,
	quick_ask_anthropic_thinking_budget: null,
	quick_ask_gemini_thinking_budget: null,
	quick_ask_gemini_thinking_level: null,
	cerebras_free_tier: true,
	groq_free_tier: true,
	cohere_free_tier: true,
	assemblyai_free_tier: true,
	speechmatics_free_tier: true,
	openai_reasoning_effort: null,
	anthropic_thinking_budget: null,
	gemini_thinking_budget: null,
	gemini_thinking_level: null,
	playing_audio_handling: "none",
	stt_timeout_seconds: null,
	overlay_mode: "recording_only",
	overlay_show_detailed_loading: false,
	overlay_monitor_target: "main",
	widget_position: "bottom-center",
	output_mode: "paste",
	output_hit_enter: false,
	output_clipboard_privacy_mode: false,
	output_smart_paste_protection: false,
	main_window_close_behavior: "minimize_to_tray",
	quiet_audio_gate_enabled: true,
	quiet_audio_min_duration_secs: 0.15,
	quiet_audio_rms_dbfs_threshold: -60,
	quiet_audio_peak_dbfs_threshold: -50,
	quiet_audio_require_speech: false,
	hot_mic_enabled: false,
	hot_mic_pre_roll_ms: 1500,
	mic_auto_recover_enabled: false,
	noise_gate_threshold_dbfs: null,
	audio_downmix_to_mono: true,
	audio_resample_to_16khz: false,
	audio_highpass_enabled: true,
	audio_agc_enabled: false,
	audio_noise_suppression_enabled: false,
	max_saved_recordings: 1000,
	transcription_retention_mode: "time",
	transcription_retention_amount: 1000,
	transcription_retention_unit: "days",
	transcription_retention_value: 0,
	transcription_retention_delete_recordings: false,
	recordings_retention_mode: "amount",
	recordings_retention_amount: 1000,
	recordings_retention_unit: "days",
	recordings_retention_value: 0,
	stats_retention_unit: "days",
	stats_retention_value: 30,
	stats_retention_max_bytes: 50_000_000,
	request_logs_retention_mode: "amount",
	request_logs_retention_amount: 50,
	request_logs_retention_days: 7,
	request_logs_privacy_mode: false,
	posthog_analytics_enabled: true,
	telemetry_disclosure_acknowledged_at: null,
	telemetry_disclosure_version: null,
	github_backup_gist_id: null,
	ocr_base_url: null,
	ocr_model: DEFAULT_OCR_MODEL,
	ocr_auth_mode: "none",
	ocr_prompt: "",
	ocr_max_tokens: 512,
	ocr_temperature: 0,
	ocr_top_p: 1,
	ocr_request_timeout_ms: 2000,
	ocr_context_max_chars: 8000,
	rewrite_active_window_ocr_mode: "off",
	quick_replace_active_window_ocr_mode: "off",
	quick_ask_active_window_ocr_mode: "off",
	ocr_auto_capture_timing: "on_start",
	ocr_hallucination_protection: true,
	ocr_hallucination_threshold: 2500,
	ocr_resize_max_dimension: 0,
	ocr_resize_filter: "nearest",
} satisfies Partial<AppSettings>;

export type DefaultSettingsKey = keyof typeof DEFAULT_SETTINGS_VALUES;

export function defaultSettingValue<K extends DefaultSettingsKey>(
	key: K,
): (typeof DEFAULT_SETTINGS_VALUES)[K] {
	return DEFAULT_SETTINGS_VALUES[key];
}
